name: 'Setup Tool'
description: 'Action to setup any CLI tool.'
author: 'Zachary Spar'

branding:
  icon: 'settings'
  color: 'green'

inputs:
  tarball-url:
    description: 'The tarball URL to download.'
    required: true
  name:
    description: 'The name of the tool.'
    required: false
    default: 'tool'

outputs:
  tool-path:
    description: 'The path to the tool binary.'

runs:
  using: node20
  main: dist/index.js
